alter table if exists clients drop constraint if exists FK21gyuophuha3vq8t1os4x2jtl;
alter table if exists clients_discounts drop constraint if exists FKrt6o37qlhcj1eeb85qqocoqpe;
alter table if exists clients_discounts drop constraint if exists FKtifgkp8nq68bnvg4mourk5nff;
alter table if exists discounts drop constraint if exists FKqunw1fcteebr8xvo453e0kukc;
alter table if exists items drop constraint if exists FK9dlr893inxj5ic9basm8jmhwl;
alter table if exists items drop constraint if exists FKorna371wtjmchqtlvulc7xwao;
alter table if exists orders drop constraint if exists FKm2dep9derpoaehshbkkatam3v;
alter table if exists orders drop constraint if exists FKsxfvku34v9ujavmj9ao69vo8s;
alter table if exists orders_items drop constraint if exists FKc03a4t5e1xbn9g2qp2k2umr64;
alter table if exists orders_items drop constraint if exists FKij1wwgx6o198ubsx1oulpopem;

drop table if exists addresses cascade;
drop table if exists clients cascade;
drop table if exists clients_discounts cascade;
drop table if exists discounts cascade;
drop table if exists discount_type cascade;
drop table if exists item_categories cascade;
drop table if exists item_types cascade;
drop table if exists items cascade;
drop table if exists orders cascade;
drop table if exists orders_items cascade;

drop sequence if exists hibernate_sequence;

create sequence hibernate_sequence start 1 increment 1;

create table addresses (id int8 generated by default as identity, additional_info varchar(255), country varchar(255), index int4, locality varchar(255), region varchar(255), room int4, street varchar(255), primary key (id));
create table clients (id int8 generated by default as identity, birthday varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), second_name varchar(255), telephone varchar(255), address_id int8, primary key (id));
create table clients_discounts (client_id int8 not null, discount_id int8 not null);
create table discounts (id int8 not null, value int4, discount_type_id int8, primary key (id));
create table discount_type (id int8 not null, name varchar(255), primary key (id));
create table item_categories (id int8 generated by default as identity, name varchar(255), primary key (id));
create table item_types (id int8 not null, name varchar(255), primary key (id));
create table items (id int8 generated by default as identity, name varchar(255), price float8, size float8, item_category_id int8, item_type_id int8, primary key (id));
create table orders (id int8 not null, date_closed timestamp, date_create timestamp, status varchar(255), total_price float8, client_id int8, discount_id int8, primary key (id));
create table orders_items (order_id int8 not null, item_id int8 not null);

alter table if exists clients add constraint FK21gyuophuha3vq8t1os4x2jtl foreign key (address_id) references addresses;
alter table if exists clients_discounts add constraint FKrt6o37qlhcj1eeb85qqocoqpe foreign key (discount_id) references discounts;
alter table if exists clients_discounts add constraint FKtifgkp8nq68bnvg4mourk5nff foreign key (client_id) references clients;
alter table if exists discounts add constraint FKqunw1fcteebr8xvo453e0kukc foreign key (discount_type_id) references discount_type;
alter table if exists items add constraint FK9dlr893inxj5ic9basm8jmhwl foreign key (item_category_id) references item_categories;
alter table if exists items add constraint FKorna371wtjmchqtlvulc7xwao foreign key (item_type_id) references item_types;
alter table if exists orders add constraint FKm2dep9derpoaehshbkkatam3v foreign key (client_id) references clients;
alter table if exists orders add constraint FKsxfvku34v9ujavmj9ao69vo8s foreign key (discount_id) references discounts;
alter table if exists orders_items add constraint FKc03a4t5e1xbn9g2qp2k2umr64 foreign key (item_id) references items;
alter table if exists orders_items add constraint FKij1wwgx6o198ubsx1oulpopem foreign key (order_id) references orders;